import React from "react";


function Description() {
    return (
        <div className='desc'>
            <h2>Airfoil self noise prediction</h2>
            <p>Airfoil self-noise refers to the noise generated by the airfoil itself when interacting with the airflow.
                This phenomenon occurs without external sources of noise like engines or mechanical systems.</p>
            <p>
                Predicting airfoil self-noise is essential across various engineering disciplines, primarily in aerospace and renewable energy sectors.
                In aerospace, accurate prediction of airfoil noise levels plays a pivotal role in aircraft design and operation.
                Similarly, in wind energy, where wind turbine noise can be a concern, predicting airfoil noise levels aids in designing quieter turbines,
                enhancing their acceptance and integration into populated areas while optimizing energy efficiency.
            </p>
            <p>
                The predicted numbers from airfoil self-noise models typically indicate the sound pressure level (SPL) generated by the airfoil at various conditions.
                Sound Pressure Level (SPL): The primary indicator is the SPL in decibels (dB), which quantifies the intensity of the noise produced by the airfoil. Higher SPL values indicate louder noise levels.
            </p>

            <p>
                The predicted SPL varies based on input parameters such as: <br />
                FREQUENCY: The frequency at which noise measurements are taken. (hz) <br />
                ANGLE OF ATTACK: The angle between the airfoil's chord line and the direction of airflow. (deg) <br />
                CHORD LENGTH: The length of the airfoil from leading to trailing edge.(m)<br />
                FREE STREAM VELOCITY: The speed of the undisturbed airflow approaching the airfoil.(m/s)<br />
                SUCTION SIDE DISPLACEMENT THICKNESS: The thickness of the boundary layer on the suction side of the airfoil.(m)<br />
            </p>
        </div>
    )
}

export default Description;